"""brief counterpoint

Revision ID: 34782d5e0ea5
Revises: b1e4c7a92d10
Create Date: 2026-08-30 11:12:52.227048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34782d5e0ea5'
down_revision: Union[str, None] = 'b1e4c7a92d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_briefs', sa.Column('counterpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_briefs', 'counterpoint')
    # ### end Alembic commands ###
