"""phase 2: signals and document analyses

Revision ID: 3a0a1673c757
Revises: 428df9719d82
Create Date: 2026-08-24 02:07:01.717723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a0a1673c757'
down_revision: Union[str, None] = '428df9719d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'prompt_version', name='uq_document_analyses_doc_version')
    )
    op.create_index(op.f('ix_document_analyses_document_id'), 'document_analyses', ['document_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('SENTIMENT_SHIFT', 'NEW_RISK_FACTOR', 'NOTABLE_QUOTE', 'QOQ_ANOMALY', 'GUIDANCE_CHANGE', name='signal_type'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('compared_document_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signal_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compared_document_id'], ['raw_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_occurred_at'), 'signals', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_signals_priority'), 'signals', ['priority'], unique=False)
    op.create_index(op.f('ix_signals_source_document_id'), 'signals', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_source_document_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_priority'), table_name='signals')
    op.drop_index(op.f('ix_signals_occurred_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_document_analyses_document_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    # ### end Alembic commands ###
