"""signal review and dismiss state

Revision ID: 5c66ef1fe02c
Revises: 3a0a1673c757
Create Date: 2026-08-25 01:21:18.278458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c66ef1fe02c'
down_revision: Union[str, None] = '3a0a1673c757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signals', sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'dismissed_at')
    op.drop_column('signals', 'reviewed_at')
    # ### end Alembic commands ###
