"""company briefs

Revision ID: 8a6c5fd75e9c
Revises: c4d82f1a90be
Create Date: 2026-08-26 14:38:41.486738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a6c5fd75e9c'
down_revision: Union[str, None] = 'c4d82f1a90be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('STRONG_NEGATIVE', 'NEGATIVE', 'MIXED', 'POSITIVE', 'STRONG_POSITIVE', 'QUIET', 'INSUFFICIENT', name='stance'), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('what_changed', sa.Text(), nullable=True),
    sa.Column('source_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_briefs_company_id'), 'company_briefs', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_briefs_generated_at'), 'company_briefs', ['generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_briefs_generated_at'), table_name='company_briefs')
    op.drop_index(op.f('ix_company_briefs_company_id'), table_name='company_briefs')
    op.drop_table('company_briefs')
    # ### end Alembic commands ###
