"""market reaction fields

Revision ID: dd2ea0f05388
Revises: d19852c7ffec
Create Date: 2026-08-25 02:20:01.385157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2ea0f05388'
down_revision: Union[str, None] = 'd19852c7ffec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('market_direction', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('market_magnitude', sa.String(), nullable=True))
    op.add_column('signals', sa.Column('market_horizon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'market_horizon')
    op.drop_column('signals', 'market_magnitude')
    op.drop_column('signals', 'market_direction')
    # ### end Alembic commands ###
