"""structured facts

Revision ID: f6189bcdea68
Revises: fdf87313e5c7
Create Date: 2026-08-25 20:04:57.441641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6189bcdea68'
down_revision: Union[str, None] = 'fdf87313e5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structured_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.Enum('INSIDER_TRANSACTION', 'INSTITUTIONAL_HOLDING', 'SHORT_INTEREST', 'PATENT_FILING', 'SEARCH_TREND_INDEX', 'JOB_POSTING_COUNT', 'APP_STORE_RANKING', name='fact_type'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fact_type', 'as_of_date', 'content_hash', name='uq_structured_facts_dedupe')
    )
    op.create_index('idx_structured_facts_company_type_date', 'structured_facts', ['company_id', 'fact_type', 'as_of_date'], unique=False)
    op.create_index(op.f('ix_structured_facts_company_id'), 'structured_facts', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structured_facts_company_id'), table_name='structured_facts')
    op.drop_index('idx_structured_facts_company_type_date', table_name='structured_facts')
    op.drop_table('structured_facts')
    # ### end Alembic commands ###
