"""document search index

Revision ID: fdf87313e5c7
Revises: a7c31e94b02f
Create Date: 2026-08-25 12:05:44.139275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdf87313e5c7'
down_revision: Union[str, None] = 'a7c31e94b02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_search_index',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False),
    sa.Column('content_chars', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    # Autogenerate cannot infer this: without a GIN index every search is a
    # sequential scan that recomputes the match for every stored document, and
    # the tsvector column exists precisely to avoid that.
    op.create_index(
        "ix_document_search_index_vector",
        "document_search_index",
        ["search_vector"],
        postgresql_using="gin",
    )


def downgrade() -> None:
    op.drop_index("ix_document_search_index_vector", table_name="document_search_index")
    op.drop_table('document_search_index')
